### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by furai** [m-atthieu/tbs.desile.fr#1]
Hey,

Do you mind freeing for me "Furai" nickname? I'm recognised everywhere by this nick and I'd like to have it here as well.

Cheers,
Furai

**Comment by m-atthieu** [comment]
nickname on which platform ? github or tbs ?

**Comment by furai** [comment]
Github. 

I'd be really grateful if you could do this for me.

**Comment by m-atthieu** [comment]
go ahead

**Comment by furai** [comment]
Thank you very much. :)
